version: "3"

services:
#  frontend:
#    container_name: frontend
#    build:
#      context: ./mir-movie-client
#      dockerfile: Dockerfile.dev
#    environment:
#      CHOKIDAR_USEPOLLING: "true"
#    volumes:
#      - ./mir-movie-client/src:/app/src
#
#  backend:
#    container_name: backend
#    build:
#      context: ./mir-movie-server
#      dockerfile: Dockerfile.dev
#    environment:
#      CHOKIDAR_USEPOLLING: "true"
#    volumes:
#      - ./mir-movie-server/src:/app/src
#
#  nginx:
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
#    container_name: nginx
#    ports:
#      - 80:80
#    depends_on:
#      - frontend
#      - backend

  postgres:
    container_name: postgres
    image: postgres:10-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}